// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "XXXX";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLeftDoorChange();
void onRightDoorChange();
void onSpeedDoorChange();

CloudDimmedLight leftDoor;
CloudDimmedLight rightDoor;
CloudDimmedLight speedDoor;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(leftDoor, READWRITE, ON_CHANGE, onLeftDoorChange);
  ArduinoCloud.addProperty(rightDoor, READWRITE, ON_CHANGE, onRightDoorChange);
  ArduinoCloud.addProperty(speedDoor, READWRITE, ON_CHANGE, onSpeedDoorChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
